<a href="https://colab.research.google.com/github/thariqziyad/data-wrangling/blob/main/Index_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook I arrange the index using a multiindex object to create a dataframe with multilevel index

In [ ]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Data Market.csv')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116
0,NaN,1,2,3,4,5,6,7,8,9,...,107,108,109,110,111,112,113,114,115,116
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dividen per Share,NaN,...,EBITDA/shares,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ticker
2,14:59:02,Ticker,Last Update,Index,Last Price,Shares Out,Market Cap,TP Consensus,2016,2017,...,2016,2017,2018,2019,2020,2021,2022,2023E,2024E,EPS
3,AALI IJ Equity,AALI,4/10/2023,IDXNCYC,8300,"1,925","15,974,913,163,900","9,166.88",469.00,470.00,...,"1,947.46","2,202.93","1,863.20","1,176.30","1,651.73","2,448.25","1,899.99",#N/A Mandatory parameter [FIELD] cannot be em...,#N/A Mandatory parameter [FIELD] cannot be em...,9.25
4,ABBA IJ Equity,ABBA,4/10/2023,IDXCYC,105,"3,936","413,268,749,985",-,-,-,...,(1.35),1.32,(8.23),(6.33),(11.78),(6.09),#N/A N/A,#N/A Mandatory parameter [FIELD] cannot be em...,#N/A Mandatory parameter [FIELD] cannot be em...,#N/A N/A

We see that the headers do not make sense. We drop the first row and drop the first column as it is redundant with the second column, and use said second column as the index. Finally, we transpose the Dataframe for ease of constructing the multilevel index.

In [ ]:
df = pd.read_csv('Data Market.csv')
df = df.drop(0)
df.index = df.loc[:,'Unnamed: 1']
df.index.names = [df.index[1]]
df = df.drop(columns=['Unnamed: 0','Unnamed: 1']).T

df.head(10)

Ticker,NaN,Ticker,AALI,ABBA,ABDA,ABMM,ACES,ACST,ADCP,ADES,...,WSKT,WTON,YELO,YPAS,YULE,ZATA,ZBRA,ZINC,ZONE,ZYRX
Unnamed: 2,NaN,Last Update,4/10/2023,4/10/2023,3/15/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023,...,4/10/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023,4/10/2023
Unnamed: 3,NaN,Index,IDXNCYC,IDXCYC,IDXFIN,IDXINDUS,IDXCYC,IDXINFRA,IDXPROP,IDXNCYC,...,IDXINFRA,IDXBASIC,IDXCYC,IDXBASIC,IDXFIN,IDXCYC,IDXINDUS,IDXBASIC,IDXCYC,IDXTECH
Unnamed: 4,NaN,Last Price,8300,105,6475,3250,444,127,58,7300,...,199,165,52,580,2200,69,478,50,1185,298
Unnamed: 5,NaN,Shares Out,"1,925","3,936",621,"2,753","17,150","12,675","22,222",590,...,"28,807","8,715","1,913",668,"1,785","8,496","2,511","25,250",870,"1,333"
Unnamed: 6,NaN,Market Cap,"15,974,913,163,900","413,268,749,985","4,019,723,253,000","8,947,786,250,000","7,648,900,000,000","1,609,745,320,000","1,288,888,887,600","4,306,246,640,000",...,"5,732,554,596,184","1,438,051,989,000","99,464,269,060","387,440,051,620","3,927,000,000,000","586,224,000,000","1,200,117,593,714","1,262,500,000,000","1,031,153,201,430","397,333,697,688"
Unnamed: 7,NaN,TP Consensus,"9,166.88",-,-,-,565.91,-,136.00,-,...,693.00,270.00,-,-,-,-,-,-,-,-
Unnamed: 8,Dividen per Share,2016,469.00,-,90.00,-,16.47,20.95,#N/A N/A,-,...,33.66,9.80,#N/A N/A,-,-,#N/A N/A,-,#N/A N/A,#N/A N/A,#N/A N/A
Unnamed: 9,NaN,2017,470.00,-,90.00,-,22.81,31.16,#N/A N/A,-,...,50.83,12.13,#N/A N/A,-,-,#N/A N/A,-,#N/A N/A,#N/A N/A,#N/A N/A
Unnamed: 10,NaN,2018,336.00,-,90.00,0.00,28.25,2.69,#N/A N/A,-,...,64.87,17.50,-,#N/A N/A,-,#N/A N/A,#N/A N/A,0.08,-,#N/A N/A
Unnamed: 11,NaN,2019,49.00,#N/A N/A,60.00,0.00,18.10,-,#N/A N/A,-,...,3.07,15.36,-,-,-,#N/A N/A,#N/A N/A,-,-,#N/A N/A

We then move the first six rows of the second column to the first, and we fill all the empty rows of the first column.

In [ ]:
df_index = df.iloc[:,0:2].ffill().bfill(axis=1)
df_index.iloc[:6,1]=' '
df_index.head(10)

Ticker                     NaN Ticker
Unnamed: 2         Last Update
Unnamed: 3               Index
Unnamed: 4          Last Price
Unnamed: 5          Shares Out
Unnamed: 6          Market Cap
Unnamed: 7        TP Consensus
Unnamed: 8   Dividen per Share   2016
Unnamed: 9   Dividen per Share   2017
Unnamed: 10  Dividen per Share   2018
Unnamed: 11  Dividen per Share   2019

Finally, we set `df_index` as the new index, we remove the decrepit columns, and we tranpose the Dataframe to return to its original orientation.

In [ ]:
mult_index = pd.MultiIndex.from_frame(df_index, names=['Name', 'Year'])
df_header = df.iloc[:,2:].set_index(mult_index,drop=True).T

df_header.head(10)

Name   Last Update     Index Last Price Shares Out            Market Cap  \
Year
Ticker
AALI     4/10/2023   IDXNCYC       8300     1,925    15,974,913,163,900
ABBA     4/10/2023    IDXCYC        105     3,936       413,268,749,985
ABDA     3/15/2023    IDXFIN       6475       621     4,019,723,253,000
ABMM     4/10/2023  IDXINDUS       3250     2,753     8,947,786,250,000
ACES     4/10/2023    IDXCYC        444    17,150     7,648,900,000,000
ACST     4/10/2023  IDXINFRA        127    12,675     1,609,745,320,000
ADCP     4/10/2023   IDXPROP         58    22,222     1,288,888,887,600
ADES     4/10/2023   IDXNCYC       7300       590     4,306,246,640,000
ADHI     4/10/2023  IDXINFRA        400     8,408     3,363,043,591,600
ADMF     4/10/2023    IDXFIN      10575     1,000    10,575,000,000,000

Name   TP Consensus Dividen per Share                                      \
Year                             2016        2017        2018        2019
Ticker
AALI      9,166.88            469.00      470.00      336.00       49.00
ABBA             -               -           -           -      #N/A N/A
ABDA             -             90.00       90.00       90.00       60.00
ABMM             -               -           -          0.00        0.00
ACES        565.91             16.47       22.81       28.25       18.10
ACST             -             20.95       31.16        2.69         -
ADCP        136.00          #N/A N/A    #N/A N/A    #N/A N/A    #N/A N/A
ADES             -               -           -           -           -
ADHI        639.99             24.18       26.51       33.13    #N/A N/A
ADMF             -            505.00      505.00      908.00    1,055.00

Name    ... EBITDA/shares                                                  \
Year    ...          2016        2017        2018        2019        2020
Ticker  ...
AALI    ...     1,947.46    2,202.93    1,863.20    1,176.30    1,651.73
ABBA    ...        (1.35)       1.32       (8.23)      (6.33)     (11.78)
ABDA    ...     #N/A N/A    #N/A N/A    #N/A N/A    #N/A N/A    #N/A N/A
ABMM    ...         0.05        0.05        0.08        0.04        0.03
ACES    ...        55.62       60.84       76.39      103.31       83.40
ACST    ...       211.66      305.07      477.31     (235.37)    (401.36)
ADCP    ...     #N/A N/A    #N/A N/A    #N/A N/A    #N/A N/A    #N/A N/A
ADES    ...       184.14      132.34      220.25      279.29      350.75
ADHI    ...       184.33      410.31      375.44      279.86      231.68
ADMF    ...     3,730.02    3,986.16    4,314.99    4,952.43    3,474.15

Name                            \
Year          2021        2022
Ticker
AALI     2,448.25    1,899.99
ABBA        (6.09)   #N/A N/A
ABDA     #N/A N/A    #N/A N/A
ABMM         0.13        0.18
ACES        78.08       76.14
ACST       (62.26)     (30.33)
ADCP     #N/A N/A        5.28
ADES       625.10      838.05
ADHI       252.70      201.56
ADMF     2,894.74    2,946.88

Name                                                       \
Year                                                2023E
Ticker
AALI     #N/A Mandatory parameter [FIELD] cannot be em...
ABBA     #N/A Mandatory parameter [FIELD] cannot be em...
ABDA     #N/A Mandatory parameter [FIELD] cannot be em...
ABMM     #N/A Mandatory parameter [FIELD] cannot be em...
ACES     #N/A Mandatory parameter [FIELD] cannot be em...
ACST     #N/A Mandatory parameter [FIELD] cannot be em...
ADCP     #N/A Mandatory parameter [FIELD] cannot be em...
ADES     #N/A Mandatory parameter [FIELD] cannot be em...
ADHI     #N/A Mandatory parameter [FIELD] cannot be em...
ADMF     #N/A Mandatory parameter [FIELD] cannot be em...

Name                                                           Ticker
Year                                                2024E         EPS
Ticker
AALI     #N/A Mandatory parameter [FIELD] cannot be em...       9.25
ABBA     #N/A Mandatory parameter [FIELD] cannot be em...   #N/A N/A
ABDA     #N/A Mandatory parameter [FIELD] cannot be em...      32.87
ABMM     #N/A Mandatory parameter [FIELD] cannot be em...       2.22
ACES     #N/A Mandatory parameter [FIELD] cannot be em...      11.44
ACST     #N/A Mandatory parameter [FIELD] cannot be em...   #N/A N/A
ADCP     #N/A Mandatory parameter [FIELD] cannot be em...      11.67
ADES     #N/A Mandatory parameter [FIELD] cannot be em...      11.80
ADHI     #N/A Mandatory parameter [FIELD] cannot be em...      28.04
ADMF     #N/A Mandatory parameter [FIELD] cannot be em...       6.59

[10 rows x 115 columns]

In [ ]:
df_header.isnull().sum()

Name           Year
Last Update              0
Index                    0
Last Price              59
Shares Out               0
Market Cap               0
                        ..
EBITDA/shares  2021      0
               2022      0
               2023E     0
               2024E     0
Ticker         EPS       0
Length: 115, dtype: int64

In [ ]:
for i in df_header.T.index:
  print(df_header.T.ADHI[i])

4/10/2023
IDXINFRA
400
 8,408
 3,363,043,591,600
 639.99
 24.18
 26.51
 33.13
 #N/A N/A
 -
 -
 #N/A N/A
 1.90
 2.50
 1,397.13
 1,506.67
 1,613.45
 1,751.16
 1,426.71
 1,439.96
 998.26
 984.50
 1,008.80
 80.60
 132.77
 165.73
 170.31
 6.16
 14.19
 17.67
 #N/A N/A
 #N/A N/A
 23.63
 13.00
 8.76
 6.32
 228.08
 57.74
 27.39
 #N/A N/A
 #N/A N/A
 1.4
 1.1
 0.9
 0.6
 1.0
 0.6
 0.6
 984.5
 1,008.8
 5.92
 9.13
 10.62
 10.15
 0.39
 0.99
 1.16
 1.90
 2.50
 1.70
 2.13
 2.21
 1.99
 0.06
 0.14
 0.20
nan
nan
 #N/A N/A
 #N/A N/A
 #N/A N/A
 #N/A N/A
 #N/A N/A
 #N/A N/A
 #N/A N/A
nan
nan
 73.90
 141.87
 136.09
 153.96
 175.28
 186.05
 #N/A Mandatory parameter [FIELD] cannot be empty
nan
 #N/A Mandatory parameter [FIELD] cannot be empty
 716,829
 1,595,634
 1,460,047
 1,088,354
 900,990
 982,715
 1,647,500
nan
 #N/A Mandatory parameter [FIELD] cannot be empty
 5.96
 9.74
 8.18
 5.96
 6.39
 6.74
 0.09
 0.09
 0.09
 184.33
 410.31
 375.44
 279.86
 231.68
 252.70
 201.56
 #N/A Mandatory parameter [FIELD] cannot be empty
 #N/A Mandatory parameter [FIELD] cannot be empty
 28.04